// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protofiles/proto.proto

package protofiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bidder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BidderId int32  `protobuf:"varint,1,opt,name=BidderId,proto3" json:"BidderId,omitempty"`
	Addr     string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Bid      int64  `protobuf:"varint,3,opt,name=Bid,proto3" json:"Bid,omitempty"`
}

func (x *Bidder) Reset() {
	*x = Bidder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bidder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bidder) ProtoMessage() {}

func (x *Bidder) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bidder.ProtoReflect.Descriptor instead.
func (*Bidder) Descriptor() ([]byte, []int) {
	return file_protofiles_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Bidder) GetBidderId() int32 {
	if x != nil {
		return x.BidderId
	}
	return 0
}

func (x *Bidder) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Bidder) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

type AuctionUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HighestBid      int64 `protobuf:"varint,1,opt,name=HighestBid,proto3" json:"HighestBid,omitempty"`
	HighestBidderId int32 `protobuf:"varint,2,opt,name=HighestBidderId,proto3" json:"HighestBidderId,omitempty"`
}

func (x *AuctionUpdate) Reset() {
	*x = AuctionUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuctionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionUpdate) ProtoMessage() {}

func (x *AuctionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionUpdate.ProtoReflect.Descriptor instead.
func (*AuctionUpdate) Descriptor() ([]byte, []int) {
	return file_protofiles_proto_proto_rawDescGZIP(), []int{1}
}

func (x *AuctionUpdate) GetHighestBid() int64 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *AuctionUpdate) GetHighestBidderId() int32 {
	if x != nil {
		return x.HighestBidderId
	}
	return 0
}

type ResultAuctionUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuctionOver     bool  `protobuf:"varint,1,opt,name=AuctionOver,proto3" json:"AuctionOver,omitempty"`
	WinningBid      int64 `protobuf:"varint,2,opt,name=WinningBid,proto3" json:"WinningBid,omitempty"`
	WinningBidderId int32 `protobuf:"varint,3,opt,name=WinningBidderId,proto3" json:"WinningBidderId,omitempty"`
}

func (x *ResultAuctionUpdate) Reset() {
	*x = ResultAuctionUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultAuctionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAuctionUpdate) ProtoMessage() {}

func (x *ResultAuctionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAuctionUpdate.ProtoReflect.Descriptor instead.
func (*ResultAuctionUpdate) Descriptor() ([]byte, []int) {
	return file_protofiles_proto_proto_rawDescGZIP(), []int{2}
}

func (x *ResultAuctionUpdate) GetAuctionOver() bool {
	if x != nil {
		return x.AuctionOver
	}
	return false
}

func (x *ResultAuctionUpdate) GetWinningBid() int64 {
	if x != nil {
		return x.WinningBid
	}
	return 0
}

func (x *ResultAuctionUpdate) GetWinningBidderId() int32 {
	if x != nil {
		return x.WinningBidderId
	}
	return 0
}

var File_protofiles_proto_proto protoreflect.FileDescriptor

var file_protofiles_proto_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x52, 0x50, 0x43, 0x22, 0x4a,
	0x0a, 0x06, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x64, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x42, 0x69, 0x64, 0x64,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x42, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x0d, 0x41, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x48,
	0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x48,
	0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x48, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x42, 0x69, 0x64,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x76, 0x65, 0x72, 0x12,
	0x1e, 0x0a, 0x0a, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x12,
	0x28, 0x0a, 0x0f, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x57, 0x69, 0x6e, 0x6e, 0x69, 0x6e,
	0x67, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x49, 0x64, 0x32, 0x6a, 0x0a, 0x07, 0x41, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x12, 0x0c, 0x2e, 0x67, 0x52,
	0x50, 0x43, 0x2e, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x67, 0x52, 0x50, 0x43,
	0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x30, 0x01,
	0x12, 0x33, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0c, 0x2e, 0x67, 0x52, 0x50,
	0x43, 0x2e, 0x42, 0x69, 0x64, 0x64, 0x65, 0x72, 0x1a, 0x19, 0x2e, 0x67, 0x52, 0x50, 0x43, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x64, 0x69, 0x73, 0x79, 0x73, 0x2d, 0x68,
	0x61, 0x6e, 0x64, 0x69, 0x6e, 0x35, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_proto_proto_rawDescOnce sync.Once
	file_protofiles_proto_proto_rawDescData = file_protofiles_proto_proto_rawDesc
)

func file_protofiles_proto_proto_rawDescGZIP() []byte {
	file_protofiles_proto_proto_rawDescOnce.Do(func() {
		file_protofiles_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_proto_proto_rawDescData)
	})
	return file_protofiles_proto_proto_rawDescData
}

var file_protofiles_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protofiles_proto_proto_goTypes = []interface{}{
	(*Bidder)(nil),              // 0: gRPC.Bidder
	(*AuctionUpdate)(nil),       // 1: gRPC.AuctionUpdate
	(*ResultAuctionUpdate)(nil), // 2: gRPC.ResultAuctionUpdate
}
var file_protofiles_proto_proto_depIdxs = []int32{
	0, // 0: gRPC.Auction.Bid:input_type -> gRPC.Bidder
	0, // 1: gRPC.Auction.Result:input_type -> gRPC.Bidder
	1, // 2: gRPC.Auction.Bid:output_type -> gRPC.AuctionUpdate
	2, // 3: gRPC.Auction.Result:output_type -> gRPC.ResultAuctionUpdate
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_proto_proto_init() }
func file_protofiles_proto_proto_init() {
	if File_protofiles_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bidder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuctionUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultAuctionUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_proto_proto_goTypes,
		DependencyIndexes: file_protofiles_proto_proto_depIdxs,
		MessageInfos:      file_protofiles_proto_proto_msgTypes,
	}.Build()
	File_protofiles_proto_proto = out.File
	file_protofiles_proto_proto_rawDesc = nil
	file_protofiles_proto_proto_goTypes = nil
	file_protofiles_proto_proto_depIdxs = nil
}
